import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import NightSky from "./components/NightSky";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "#0a0a1a",
          color: "#fffae3",
          fontFamily: "'Lora', serif",
        }}
        className="min-h-screen antialiased"
      >
        <Toaster position="top-center" />
        <main className="relative z-10">
          {children}
        </main>
      </body>
    </html>
  );
}
